// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

void execute_one(void)
{
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  perf_event_open arguments: [
  //    attr: ptr[in, perf_event_attr] {
  //      perf_event_attr {
  //        type: perf_event_type = 0x4 (4 bytes)
  //        size: len = 0x80 (4 bytes)
  //        config0: int8 = 0x1 (1 bytes)
  //        config1: int8 = 0x35 (1 bytes)
  //        config2: int8 = 0x8 (1 bytes)
  //        config3: int8 = 0xe (1 bytes)
  //        config4: const = 0xf5 (4 bytes)
  //        sample_freq: int64 = 0xfdf3 (8 bytes)
  //        sample_type: perf_sample_type = 0xa04 (8 bytes)
  //        read_format: perf_read_format = 0x9 (8 bytes)
  //        disabled: int64 = 0x0 (0 bytes)
  //        inherit: int64 = 0x1 (0 bytes)
  //        pinned: int64 = 0x1 (0 bytes)
  //        exclusive: int64 = 0x0 (0 bytes)
  //        exclude_user: int64 = 0x0 (0 bytes)
  //        exclude_kernel: int64 = 0x1 (0 bytes)
  //        exclude_hv: int64 = 0x1 (0 bytes)
  //        exclude_idle: int64 = 0x0 (0 bytes)
  //        mmap: int64 = 0x0 (0 bytes)
  //        comm: int64 = 0x1 (0 bytes)
  //        freq: int64 = 0x1 (0 bytes)
  //        inherit_stat: int64 = 0x1 (0 bytes)
  //        enable_on_exec: int64 = 0x0 (0 bytes)
  //        task: int64 = 0x0 (0 bytes)
  //        watermark: int64 = 0x0 (0 bytes)
  //        precise_ip: int64 = 0x0 (0 bytes)
  //        mmap_data: int64 = 0x1 (0 bytes)
  //        sample_id_all: int64 = 0x0 (0 bytes)
  //        exclude_host: int64 = 0x1 (0 bytes)
  //        exclude_guest: int64 = 0x1 (0 bytes)
  //        exclude_callchain_kernel: int64 = 0x0 (0 bytes)
  //        exclude_callchain_user: int64 = 0x1 (0 bytes)
  //        mmap2: int64 = 0x1 (0 bytes)
  //        comm_exec: int64 = 0x1 (0 bytes)
  //        use_clockid: int64 = 0x0 (0 bytes)
  //        context_switch: int64 = 0x1 (0 bytes)
  //        write_backward: int64 = 0x1 (0 bytes)
  //        namespaces: int64 = 0x1 (0 bytes)
  //        ksymbol: int64 = 0x0 (0 bytes)
  //        bpf_event: int64 = 0x1 (0 bytes)
  //        aux_output: int64 = 0x0 (0 bytes)
  //        cgroup: int64 = 0x1 (0 bytes)
  //        text_poke: int64 = 0x1 (0 bytes)
  //        build_id: int64 = 0x1 (0 bytes)
  //        inherit_thread: int64 = 0x0 (0 bytes)
  //        remove_on_exec: int64 = 0x0 (0 bytes)
  //        sigtrap: int64 = 0x0 (0 bytes)
  //        __reserved_1: const = 0x0 (8 bytes)
  //        wakeup_events: int32 = 0x6 (4 bytes)
  //        bp_type: perf_bp_type = 0x0 (4 bytes)
  //        bp_config: union perf_bp_config {
  //          perf_config_ext: perf_config_ext {
  //            config1: int64 = 0xa4 (8 bytes)
  //            config2: int64 = 0x9 (8 bytes)
  //          }
  //        }
  //        branch_sample_type: perf_branch_sample_type = 0x80 (8 bytes)
  //        sample_regs_user: int64 = 0x0 (8 bytes)
  //        sample_stack_user: int32 = 0xfffffff8 (4 bytes)
  //        clockid: clock_type = 0x8 (4 bytes)
  //        sample_regs_intr: int64 = 0x5 (8 bytes)
  //        aux_watermark: int32 = 0x80000001 (4 bytes)
  //        sample_max_stack: int16 = 0x4 (2 bytes)
  //        __reserved_2: const = 0x0 (2 bytes)
  //        aux_sample_size: int32 = 0x0 (4 bytes)
  //        __reserved_3: const = 0x0 (4 bytes)
  //        sig_data: int64 = 0x1001 (8 bytes)
  //      }
  //    }
  //    pid: pid (resource)
  //    cpu: intptr = 0xffffffffffffffff (8 bytes)
  //    group: fd_perf (resource)
  //    flags: perf_flags = 0x8 (8 bytes)
  //  ]
  //  returns fd_perf
  *(uint32_t*)0x200000000dc0 = 4;
  *(uint32_t*)0x200000000dc4 = 0x80;
  *(uint8_t*)0x200000000dc8 = 1;
  *(uint8_t*)0x200000000dc9 = 0x35;
  *(uint8_t*)0x200000000dca = 8;
  *(uint8_t*)0x200000000dcb = 0xe;
  *(uint32_t*)0x200000000dcc = 0xf5;
  *(uint64_t*)0x200000000dd0 = 0xfdf3;
  *(uint64_t*)0x200000000dd8 = 0xa04;
  *(uint64_t*)0x200000000de0 = 9;
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 1, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000000de8, 0, 38, 26);
  *(uint32_t*)0x200000000df0 = 6;
  *(uint32_t*)0x200000000df4 = 0;
  *(uint64_t*)0x200000000df8 = 0xa4;
  *(uint64_t*)0x200000000e00 = 9;
  *(uint64_t*)0x200000000e08 = 0x80;
  *(uint64_t*)0x200000000e10 = 0;
  *(uint32_t*)0x200000000e18 = 0xfffffff8;
  *(uint32_t*)0x200000000e1c = 8;
  *(uint64_t*)0x200000000e20 = 5;
  *(uint32_t*)0x200000000e28 = 0x80000001;
  *(uint16_t*)0x200000000e2c = 4;
  *(uint16_t*)0x200000000e2e = 0;
  *(uint32_t*)0x200000000e30 = 0;
  *(uint32_t*)0x200000000e34 = 0;
  *(uint64_t*)0x200000000e38 = 0x1001;
  syscall(__NR_perf_event_open, /*attr=*/0x200000000dc0ul, /*pid=*/0,
          /*cpu=*/(intptr_t)-1, /*group=*/(intptr_t)-1,
          /*flags=PERF_FLAG_FD_CLOEXEC*/ 8ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  loop();
  return 0;
}
