// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  openat$comedi arguments: [
  //    fd: const = 0xffffffffffffff9c (8 bytes)
  //    file: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 63 6f 6d 65 64 69 32 00} (length 0xd)
  //    }
  //    flags: open_flags = 0x20000 (4 bytes)
  //    mode: const = 0x0 (2 bytes)
  //  ]
  //  returns fd_comedi
  memcpy((void*)0x200000000000, "/dev/comedi2\000", 13);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul,
                /*file=*/0x200000000000ul, /*flags=O_NOFOLLOW*/ 0x20000,
                /*mode=*/0);
  if (res != -1)
    r[0] = res;
  //  ioctl$COMEDI_DEVCONFIG arguments: [
  //    fd: fd_comedi (resource)
  //    cmd: const = 0x40946400 (4 bytes)
  //    arg: ptr[in, comedi_devconfig] {
  //      comedi_devconfig {
  //        board_name: buffer: {38 32 35 35 00 00 00 00 00 00 00 00 00 00 00 00
  //        00 00 00 00} (length 0x14) options: array[int32] {
  //          int32 = 0x10 (4 bytes)
  //          int32 = 0x8000 (4 bytes)
  //          int32 = 0x6 (4 bytes)
  //          int32 = 0xffffffff (4 bytes)
  //          int32 = 0xc000000 (4 bytes)
  //          int32 = 0x8 (4 bytes)
  //          int32 = 0x2 (4 bytes)
  //          int32 = 0x9f06 (4 bytes)
  //          int32 = 0x6 (4 bytes)
  //          int32 = 0x80000000 (4 bytes)
  //          int32 = 0x5 (4 bytes)
  //          int32 = 0x9 (4 bytes)
  //          int32 = 0x7fff (4 bytes)
  //          int32 = 0xe40 (4 bytes)
  //          int32 = 0xe (4 bytes)
  //          int32 = 0xffff (4 bytes)
  //          int32 = 0x7f (4 bytes)
  //          int32 = 0xf3c0 (4 bytes)
  //          int32 = 0x401 (4 bytes)
  //          int32 = 0x6 (4 bytes)
  //          int32 = 0xf (4 bytes)
  //          int32 = 0x5 (4 bytes)
  //          int32 = 0x1 (4 bytes)
  //          int32 = 0x1 (4 bytes)
  //          int32 = 0x7b (4 bytes)
  //          int32 = 0x9 (4 bytes)
  //          int32 = 0x5 (4 bytes)
  //          int32 = 0x7 (4 bytes)
  //          int32 = 0x100 (4 bytes)
  //          int32 = 0x80000000 (4 bytes)
  //          int32 = 0x3 (4 bytes)
  //          int32 = 0x0 (4 bytes)
  //        }
  //      }
  //    }
  //  ]
  memcpy((void*)0x200000000040,
         "8255\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000",
         20);
  *(uint32_t*)0x200000000054 = 0x10;
  *(uint32_t*)0x200000000058 = 0x8000;
  *(uint32_t*)0x20000000005c = 6;
  *(uint32_t*)0x200000000060 = -1;
  *(uint32_t*)0x200000000064 = 0xc000000;
  *(uint32_t*)0x200000000068 = 8;
  *(uint32_t*)0x20000000006c = 2;
  *(uint32_t*)0x200000000070 = 0x9f06;
  *(uint32_t*)0x200000000074 = 6;
  *(uint32_t*)0x200000000078 = 0x80000000;
  *(uint32_t*)0x20000000007c = 5;
  *(uint32_t*)0x200000000080 = 9;
  *(uint32_t*)0x200000000084 = 0x7fff;
  *(uint32_t*)0x200000000088 = 0xe40;
  *(uint32_t*)0x20000000008c = 0xe;
  *(uint32_t*)0x200000000090 = 0xffff;
  *(uint32_t*)0x200000000094 = 0x7f;
  *(uint32_t*)0x200000000098 = 0xf3c0;
  *(uint32_t*)0x20000000009c = 0x401;
  *(uint32_t*)0x2000000000a0 = 6;
  *(uint32_t*)0x2000000000a4 = 0xf;
  *(uint32_t*)0x2000000000a8 = 5;
  *(uint32_t*)0x2000000000ac = 1;
  *(uint32_t*)0x2000000000b0 = 1;
  *(uint32_t*)0x2000000000b4 = 0x7b;
  *(uint32_t*)0x2000000000b8 = 9;
  *(uint32_t*)0x2000000000bc = 5;
  *(uint32_t*)0x2000000000c0 = 7;
  *(uint32_t*)0x2000000000c4 = 0x100;
  *(uint32_t*)0x2000000000c8 = 0x80000000;
  *(uint32_t*)0x2000000000cc = 3;
  *(uint32_t*)0x2000000000d0 = 0;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x40946400,
          /*arg=*/0x200000000040ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  loop();
  return 0;
}
